load("@rules_derivita_ts//js:index.bzl", "js_library")

package(default_visibility = ["//visibility:public"])

js_library(
    name = "flags",
    srcs = ["flags.js", "flags.d.ts"],
    lenient = True,
)
