//!! generated by clutz.
// Generated from net/xpc/relay.js
declare namespace ಠ_ಠ.clutz.goog.net.xpc {
  let relay : { } ;
}
declare module 'goog:goog.net.xpc.relay' {
  import relay = ಠ_ಠ.clutz.goog.net.xpc.relay;
  export default relay;
}
