//!! generated by clutz.
// Generated from storage/mechanism/mechanism.js
declare namespace ಠ_ಠ.clutz.goog.storage.mechanism {
  /**
   * Basic interface for all storage mechanisms.
   */
  abstract class Mechanism {
    private noStructuralTyping_goog_storage_mechanism_Mechanism : any;
    /**
     * Get the value stored under a key.
     * @param key The key to get.
     */
    abstract get (key : string ) : string | null ;
    /**
     * Remove a key and its value.
     * @param key The key to remove.
     */
    abstract remove (key : string ) : void ;
    /**
     * Set a value for a key.
     * @param key The key to set.
     * @param value The string to save.
     */
    abstract set (key : string , value : string ) : void ;
  }
}
declare module 'goog:goog.storage.mechanism.Mechanism' {
  import Mechanism = ಠ_ಠ.clutz.goog.storage.mechanism.Mechanism;
  export default Mechanism;
}
