//!! generated by clutz.
// Generated from net/streams/base64pbstreamparser.js
declare namespace ಠ_ಠ.clutz {
  /**
   * The default base64-encoded Protobuf stream parser.
   */
  class module$exports$goog$net$streams$Base64PbStreamParser implements ಠ_ಠ.clutz.module$exports$goog$net$streams$StreamParser {
    private noStructuralTyping_module$exports$goog$net$streams$Base64PbStreamParser : any;
    acceptsBinaryInput ( ) : boolean ;
    getErrorMessage ( ) : any ;
    isInputValid ( ) : any ;
    parse (input ? : any ) : any ;
  }
}
declare module 'goog:goog.net.streams.Base64PbStreamParser' {
  import Base64PbStreamParser = ಠ_ಠ.clutz.module$exports$goog$net$streams$Base64PbStreamParser;
  export default Base64PbStreamParser;
}
