//!! generated by clutz.
// Generated from graphics/ext/image.js
declare namespace ಠ_ಠ.clutz.goog.graphics.ext {
  /**
   * Wrapper for a graphics image element.
   */
  class Image extends ಠ_ಠ.clutz.goog.graphics.ext.Element {
    private noStructuralTyping_goog_graphics_ext_Image : any;
    /**
     * Wrapper for a graphics image element.
     * @param group Parent for this element.
     * @param src The path to the image to display.
     */
    constructor (group : ಠ_ಠ.clutz.goog.graphics.ext.Group | null , src : string ) ;
    /**
     * Redraw the image.  Called when the coordinate system is changed.
     */
    protected redraw ( ) : void ;
    /**
     * Update the source of the image.
     * @param src Source of the image.
     */
    setSource (src : string ) : void ;
  }
}
declare module 'goog:goog.graphics.ext.Image' {
  import Image = ಠ_ಠ.clutz.goog.graphics.ext.Image;
  export default Image;
}
