//!! generated by clutz.
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  let DateTimeSymbols : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols' {
  import DateTimeSymbols = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols;
  export default DateTimeSymbols;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  interface DateTimeSymbolsType {
    AMPMS : string [] ;
    DATEFORMATS : string [] ;
    DATETIMEFORMATS : string [] ;
    ERANAMES : string [] ;
    ERAS : string [] ;
    FIRSTDAYOFWEEK : number ;
    FIRSTWEEKCUTOFFDAY : number ;
    MONTHS : string [] ;
    NARROWMONTHS : string [] ;
    NARROWWEEKDAYS : string [] ;
    QUARTERS : string [] ;
    SHORTMONTHS : string [] ;
    SHORTQUARTERS : string [] ;
    SHORTWEEKDAYS : string [] ;
    STANDALONEMONTHS : string [] ;
    STANDALONENARROWMONTHS : string [] ;
    STANDALONENARROWWEEKDAYS : string [] ;
    STANDALONESHORTMONTHS : string [] ;
    STANDALONESHORTWEEKDAYS : string [] ;
    STANDALONEWEEKDAYS : string [] ;
    TIMEFORMATS : string [] ;
    WEEKDAYS : string [] ;
    WEEKENDRANGE : number [] ;
    ZERODIGIT ? : number ;
  }
}
declare module 'goog:goog.i18n.DateTimeSymbolsType' {
  import DateTimeSymbolsType = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType;
  export default DateTimeSymbolsType;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale af.
   */
  let DateTimeSymbols_af : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_af' {
  import DateTimeSymbols_af = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_af;
  export default DateTimeSymbols_af;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale am.
   */
  let DateTimeSymbols_am : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_am' {
  import DateTimeSymbols_am = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_am;
  export default DateTimeSymbols_am;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale ar.
   */
  let DateTimeSymbols_ar : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_ar' {
  import DateTimeSymbols_ar = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_ar;
  export default DateTimeSymbols_ar;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale ar_DZ.
   */
  let DateTimeSymbols_ar_DZ : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_ar_DZ' {
  import DateTimeSymbols_ar_DZ = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_ar_DZ;
  export default DateTimeSymbols_ar_DZ;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale ar_EG.
   */
  let DateTimeSymbols_ar_EG : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_ar_EG' {
  import DateTimeSymbols_ar_EG = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_ar_EG;
  export default DateTimeSymbols_ar_EG;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale az.
   */
  let DateTimeSymbols_az : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_az' {
  import DateTimeSymbols_az = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_az;
  export default DateTimeSymbols_az;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale be.
   */
  let DateTimeSymbols_be : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_be' {
  import DateTimeSymbols_be = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_be;
  export default DateTimeSymbols_be;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale bg.
   */
  let DateTimeSymbols_bg : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_bg' {
  import DateTimeSymbols_bg = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_bg;
  export default DateTimeSymbols_bg;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale bn.
   */
  let DateTimeSymbols_bn : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_bn' {
  import DateTimeSymbols_bn = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_bn;
  export default DateTimeSymbols_bn;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale br.
   */
  let DateTimeSymbols_br : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_br' {
  import DateTimeSymbols_br = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_br;
  export default DateTimeSymbols_br;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale bs.
   */
  let DateTimeSymbols_bs : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_bs' {
  import DateTimeSymbols_bs = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_bs;
  export default DateTimeSymbols_bs;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale ca.
   */
  let DateTimeSymbols_ca : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_ca' {
  import DateTimeSymbols_ca = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_ca;
  export default DateTimeSymbols_ca;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale chr.
   */
  let DateTimeSymbols_chr : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_chr' {
  import DateTimeSymbols_chr = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_chr;
  export default DateTimeSymbols_chr;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale cs.
   */
  let DateTimeSymbols_cs : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_cs' {
  import DateTimeSymbols_cs = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_cs;
  export default DateTimeSymbols_cs;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale cy.
   */
  let DateTimeSymbols_cy : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_cy' {
  import DateTimeSymbols_cy = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_cy;
  export default DateTimeSymbols_cy;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale da.
   */
  let DateTimeSymbols_da : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_da' {
  import DateTimeSymbols_da = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_da;
  export default DateTimeSymbols_da;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale de.
   */
  let DateTimeSymbols_de : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_de' {
  import DateTimeSymbols_de = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_de;
  export default DateTimeSymbols_de;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale de_AT.
   */
  let DateTimeSymbols_de_AT : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_de_AT' {
  import DateTimeSymbols_de_AT = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_de_AT;
  export default DateTimeSymbols_de_AT;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale de_CH.
   */
  let DateTimeSymbols_de_CH : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_de_CH' {
  import DateTimeSymbols_de_CH = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_de_CH;
  export default DateTimeSymbols_de_CH;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale el.
   */
  let DateTimeSymbols_el : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_el' {
  import DateTimeSymbols_el = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_el;
  export default DateTimeSymbols_el;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale en.
   */
  let DateTimeSymbols_en : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_en' {
  import DateTimeSymbols_en = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_en;
  export default DateTimeSymbols_en;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale en_AU.
   */
  let DateTimeSymbols_en_AU : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_en_AU' {
  import DateTimeSymbols_en_AU = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_en_AU;
  export default DateTimeSymbols_en_AU;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale en_CA.
   */
  let DateTimeSymbols_en_CA : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_en_CA' {
  import DateTimeSymbols_en_CA = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_en_CA;
  export default DateTimeSymbols_en_CA;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale en_GB.
   */
  let DateTimeSymbols_en_GB : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_en_GB' {
  import DateTimeSymbols_en_GB = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_en_GB;
  export default DateTimeSymbols_en_GB;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale en_IE.
   */
  let DateTimeSymbols_en_IE : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_en_IE' {
  import DateTimeSymbols_en_IE = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_en_IE;
  export default DateTimeSymbols_en_IE;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale en_IN.
   */
  let DateTimeSymbols_en_IN : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_en_IN' {
  import DateTimeSymbols_en_IN = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_en_IN;
  export default DateTimeSymbols_en_IN;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale en_ISO.
   */
  let DateTimeSymbols_en_ISO : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_en_ISO' {
  import DateTimeSymbols_en_ISO = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_en_ISO;
  export default DateTimeSymbols_en_ISO;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale en_SG.
   */
  let DateTimeSymbols_en_SG : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_en_SG' {
  import DateTimeSymbols_en_SG = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_en_SG;
  export default DateTimeSymbols_en_SG;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale en_US.
   */
  let DateTimeSymbols_en_US : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_en_US' {
  import DateTimeSymbols_en_US = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_en_US;
  export default DateTimeSymbols_en_US;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale en_ZA.
   */
  let DateTimeSymbols_en_ZA : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_en_ZA' {
  import DateTimeSymbols_en_ZA = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_en_ZA;
  export default DateTimeSymbols_en_ZA;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale es.
   */
  let DateTimeSymbols_es : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_es' {
  import DateTimeSymbols_es = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_es;
  export default DateTimeSymbols_es;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale es_419.
   */
  let DateTimeSymbols_es_419 : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_es_419' {
  import DateTimeSymbols_es_419 = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_es_419;
  export default DateTimeSymbols_es_419;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale es_ES.
   */
  let DateTimeSymbols_es_ES : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_es_ES' {
  import DateTimeSymbols_es_ES = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_es_ES;
  export default DateTimeSymbols_es_ES;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale es_MX.
   */
  let DateTimeSymbols_es_MX : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_es_MX' {
  import DateTimeSymbols_es_MX = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_es_MX;
  export default DateTimeSymbols_es_MX;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale es_US.
   */
  let DateTimeSymbols_es_US : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_es_US' {
  import DateTimeSymbols_es_US = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_es_US;
  export default DateTimeSymbols_es_US;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale et.
   */
  let DateTimeSymbols_et : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_et' {
  import DateTimeSymbols_et = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_et;
  export default DateTimeSymbols_et;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale eu.
   */
  let DateTimeSymbols_eu : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_eu' {
  import DateTimeSymbols_eu = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_eu;
  export default DateTimeSymbols_eu;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale fa.
   */
  let DateTimeSymbols_fa : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_fa' {
  import DateTimeSymbols_fa = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_fa;
  export default DateTimeSymbols_fa;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale fi.
   */
  let DateTimeSymbols_fi : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_fi' {
  import DateTimeSymbols_fi = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_fi;
  export default DateTimeSymbols_fi;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale fil.
   */
  let DateTimeSymbols_fil : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_fil' {
  import DateTimeSymbols_fil = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_fil;
  export default DateTimeSymbols_fil;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale fr.
   */
  let DateTimeSymbols_fr : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_fr' {
  import DateTimeSymbols_fr = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_fr;
  export default DateTimeSymbols_fr;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale fr_CA.
   */
  let DateTimeSymbols_fr_CA : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_fr_CA' {
  import DateTimeSymbols_fr_CA = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_fr_CA;
  export default DateTimeSymbols_fr_CA;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale ga.
   */
  let DateTimeSymbols_ga : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_ga' {
  import DateTimeSymbols_ga = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_ga;
  export default DateTimeSymbols_ga;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale gl.
   */
  let DateTimeSymbols_gl : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_gl' {
  import DateTimeSymbols_gl = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_gl;
  export default DateTimeSymbols_gl;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale gsw.
   */
  let DateTimeSymbols_gsw : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_gsw' {
  import DateTimeSymbols_gsw = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_gsw;
  export default DateTimeSymbols_gsw;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale gu.
   */
  let DateTimeSymbols_gu : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_gu' {
  import DateTimeSymbols_gu = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_gu;
  export default DateTimeSymbols_gu;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale haw.
   */
  let DateTimeSymbols_haw : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_haw' {
  import DateTimeSymbols_haw = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_haw;
  export default DateTimeSymbols_haw;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale he.
   */
  let DateTimeSymbols_he : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_he' {
  import DateTimeSymbols_he = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_he;
  export default DateTimeSymbols_he;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale hi.
   */
  let DateTimeSymbols_hi : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_hi' {
  import DateTimeSymbols_hi = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_hi;
  export default DateTimeSymbols_hi;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale hr.
   */
  let DateTimeSymbols_hr : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_hr' {
  import DateTimeSymbols_hr = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_hr;
  export default DateTimeSymbols_hr;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale hu.
   */
  let DateTimeSymbols_hu : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_hu' {
  import DateTimeSymbols_hu = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_hu;
  export default DateTimeSymbols_hu;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale hy.
   */
  let DateTimeSymbols_hy : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_hy' {
  import DateTimeSymbols_hy = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_hy;
  export default DateTimeSymbols_hy;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale id.
   */
  let DateTimeSymbols_id : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_id' {
  import DateTimeSymbols_id = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_id;
  export default DateTimeSymbols_id;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale in.
   */
  let DateTimeSymbols_in : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_in' {
  import DateTimeSymbols_in = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_in;
  export default DateTimeSymbols_in;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale is.
   */
  let DateTimeSymbols_is : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_is' {
  import DateTimeSymbols_is = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_is;
  export default DateTimeSymbols_is;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale it.
   */
  let DateTimeSymbols_it : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_it' {
  import DateTimeSymbols_it = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_it;
  export default DateTimeSymbols_it;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale iw.
   */
  let DateTimeSymbols_iw : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_iw' {
  import DateTimeSymbols_iw = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_iw;
  export default DateTimeSymbols_iw;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale ja.
   */
  let DateTimeSymbols_ja : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_ja' {
  import DateTimeSymbols_ja = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_ja;
  export default DateTimeSymbols_ja;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale ka.
   */
  let DateTimeSymbols_ka : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_ka' {
  import DateTimeSymbols_ka = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_ka;
  export default DateTimeSymbols_ka;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale kk.
   */
  let DateTimeSymbols_kk : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_kk' {
  import DateTimeSymbols_kk = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_kk;
  export default DateTimeSymbols_kk;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale km.
   */
  let DateTimeSymbols_km : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_km' {
  import DateTimeSymbols_km = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_km;
  export default DateTimeSymbols_km;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale kn.
   */
  let DateTimeSymbols_kn : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_kn' {
  import DateTimeSymbols_kn = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_kn;
  export default DateTimeSymbols_kn;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale ko.
   */
  let DateTimeSymbols_ko : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_ko' {
  import DateTimeSymbols_ko = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_ko;
  export default DateTimeSymbols_ko;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale ky.
   */
  let DateTimeSymbols_ky : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_ky' {
  import DateTimeSymbols_ky = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_ky;
  export default DateTimeSymbols_ky;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale ln.
   */
  let DateTimeSymbols_ln : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_ln' {
  import DateTimeSymbols_ln = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_ln;
  export default DateTimeSymbols_ln;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale lo.
   */
  let DateTimeSymbols_lo : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_lo' {
  import DateTimeSymbols_lo = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_lo;
  export default DateTimeSymbols_lo;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale lt.
   */
  let DateTimeSymbols_lt : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_lt' {
  import DateTimeSymbols_lt = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_lt;
  export default DateTimeSymbols_lt;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale lv.
   */
  let DateTimeSymbols_lv : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_lv' {
  import DateTimeSymbols_lv = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_lv;
  export default DateTimeSymbols_lv;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale mk.
   */
  let DateTimeSymbols_mk : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_mk' {
  import DateTimeSymbols_mk = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_mk;
  export default DateTimeSymbols_mk;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale ml.
   */
  let DateTimeSymbols_ml : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_ml' {
  import DateTimeSymbols_ml = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_ml;
  export default DateTimeSymbols_ml;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale mn.
   */
  let DateTimeSymbols_mn : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_mn' {
  import DateTimeSymbols_mn = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_mn;
  export default DateTimeSymbols_mn;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale mo.
   */
  let DateTimeSymbols_mo : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_mo' {
  import DateTimeSymbols_mo = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_mo;
  export default DateTimeSymbols_mo;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale mr.
   */
  let DateTimeSymbols_mr : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_mr' {
  import DateTimeSymbols_mr = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_mr;
  export default DateTimeSymbols_mr;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale ms.
   */
  let DateTimeSymbols_ms : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_ms' {
  import DateTimeSymbols_ms = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_ms;
  export default DateTimeSymbols_ms;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale mt.
   */
  let DateTimeSymbols_mt : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_mt' {
  import DateTimeSymbols_mt = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_mt;
  export default DateTimeSymbols_mt;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale my.
   */
  let DateTimeSymbols_my : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_my' {
  import DateTimeSymbols_my = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_my;
  export default DateTimeSymbols_my;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale nb.
   */
  let DateTimeSymbols_nb : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_nb' {
  import DateTimeSymbols_nb = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_nb;
  export default DateTimeSymbols_nb;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale ne.
   */
  let DateTimeSymbols_ne : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_ne' {
  import DateTimeSymbols_ne = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_ne;
  export default DateTimeSymbols_ne;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale nl.
   */
  let DateTimeSymbols_nl : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_nl' {
  import DateTimeSymbols_nl = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_nl;
  export default DateTimeSymbols_nl;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale no.
   */
  let DateTimeSymbols_no : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_no' {
  import DateTimeSymbols_no = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_no;
  export default DateTimeSymbols_no;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale no_NO.
   */
  let DateTimeSymbols_no_NO : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_no_NO' {
  import DateTimeSymbols_no_NO = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_no_NO;
  export default DateTimeSymbols_no_NO;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale or.
   */
  let DateTimeSymbols_or : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_or' {
  import DateTimeSymbols_or = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_or;
  export default DateTimeSymbols_or;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale pa.
   */
  let DateTimeSymbols_pa : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_pa' {
  import DateTimeSymbols_pa = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_pa;
  export default DateTimeSymbols_pa;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale pl.
   */
  let DateTimeSymbols_pl : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_pl' {
  import DateTimeSymbols_pl = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_pl;
  export default DateTimeSymbols_pl;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale pt.
   */
  let DateTimeSymbols_pt : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_pt' {
  import DateTimeSymbols_pt = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_pt;
  export default DateTimeSymbols_pt;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale pt_BR.
   */
  let DateTimeSymbols_pt_BR : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_pt_BR' {
  import DateTimeSymbols_pt_BR = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_pt_BR;
  export default DateTimeSymbols_pt_BR;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale pt_PT.
   */
  let DateTimeSymbols_pt_PT : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_pt_PT' {
  import DateTimeSymbols_pt_PT = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_pt_PT;
  export default DateTimeSymbols_pt_PT;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale ro.
   */
  let DateTimeSymbols_ro : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_ro' {
  import DateTimeSymbols_ro = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_ro;
  export default DateTimeSymbols_ro;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale ru.
   */
  let DateTimeSymbols_ru : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_ru' {
  import DateTimeSymbols_ru = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_ru;
  export default DateTimeSymbols_ru;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale sh.
   */
  let DateTimeSymbols_sh : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_sh' {
  import DateTimeSymbols_sh = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_sh;
  export default DateTimeSymbols_sh;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale si.
   */
  let DateTimeSymbols_si : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_si' {
  import DateTimeSymbols_si = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_si;
  export default DateTimeSymbols_si;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale sk.
   */
  let DateTimeSymbols_sk : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_sk' {
  import DateTimeSymbols_sk = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_sk;
  export default DateTimeSymbols_sk;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale sl.
   */
  let DateTimeSymbols_sl : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_sl' {
  import DateTimeSymbols_sl = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_sl;
  export default DateTimeSymbols_sl;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale sq.
   */
  let DateTimeSymbols_sq : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_sq' {
  import DateTimeSymbols_sq = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_sq;
  export default DateTimeSymbols_sq;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale sr.
   */
  let DateTimeSymbols_sr : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_sr' {
  import DateTimeSymbols_sr = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_sr;
  export default DateTimeSymbols_sr;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale sr_Latn.
   */
  let DateTimeSymbols_sr_Latn : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_sr_Latn' {
  import DateTimeSymbols_sr_Latn = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_sr_Latn;
  export default DateTimeSymbols_sr_Latn;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale sv.
   */
  let DateTimeSymbols_sv : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_sv' {
  import DateTimeSymbols_sv = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_sv;
  export default DateTimeSymbols_sv;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale sw.
   */
  let DateTimeSymbols_sw : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_sw' {
  import DateTimeSymbols_sw = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_sw;
  export default DateTimeSymbols_sw;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale ta.
   */
  let DateTimeSymbols_ta : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_ta' {
  import DateTimeSymbols_ta = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_ta;
  export default DateTimeSymbols_ta;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale te.
   */
  let DateTimeSymbols_te : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_te' {
  import DateTimeSymbols_te = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_te;
  export default DateTimeSymbols_te;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale th.
   */
  let DateTimeSymbols_th : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_th' {
  import DateTimeSymbols_th = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_th;
  export default DateTimeSymbols_th;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale tl.
   */
  let DateTimeSymbols_tl : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_tl' {
  import DateTimeSymbols_tl = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_tl;
  export default DateTimeSymbols_tl;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale tr.
   */
  let DateTimeSymbols_tr : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_tr' {
  import DateTimeSymbols_tr = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_tr;
  export default DateTimeSymbols_tr;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale uk.
   */
  let DateTimeSymbols_uk : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_uk' {
  import DateTimeSymbols_uk = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_uk;
  export default DateTimeSymbols_uk;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale ur.
   */
  let DateTimeSymbols_ur : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_ur' {
  import DateTimeSymbols_ur = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_ur;
  export default DateTimeSymbols_ur;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale uz.
   */
  let DateTimeSymbols_uz : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_uz' {
  import DateTimeSymbols_uz = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_uz;
  export default DateTimeSymbols_uz;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale vi.
   */
  let DateTimeSymbols_vi : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_vi' {
  import DateTimeSymbols_vi = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_vi;
  export default DateTimeSymbols_vi;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale zh.
   */
  let DateTimeSymbols_zh : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_zh' {
  import DateTimeSymbols_zh = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_zh;
  export default DateTimeSymbols_zh;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale zh_CN.
   */
  let DateTimeSymbols_zh_CN : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_zh_CN' {
  import DateTimeSymbols_zh_CN = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_zh_CN;
  export default DateTimeSymbols_zh_CN;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale zh_HK.
   */
  let DateTimeSymbols_zh_HK : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_zh_HK' {
  import DateTimeSymbols_zh_HK = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_zh_HK;
  export default DateTimeSymbols_zh_HK;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale zh_TW.
   */
  let DateTimeSymbols_zh_TW : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_zh_TW' {
  import DateTimeSymbols_zh_TW = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_zh_TW;
  export default DateTimeSymbols_zh_TW;
}
// Generated from i18n/datetimesymbols.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Date/time formatting symbols for locale zu.
   */
  let DateTimeSymbols_zu : ಠ_ಠ.clutz.goog.i18n.DateTimeSymbolsType ;
}
declare module 'goog:goog.i18n.DateTimeSymbols_zu' {
  import DateTimeSymbols_zu = ಠ_ಠ.clutz.goog.i18n.DateTimeSymbols_zu;
  export default DateTimeSymbols_zu;
}
