//!! generated by clutz.
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Select date/time pattern by locale.
   */
  let DateTimePatterns : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns' {
  import DateTimePatterns = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns;
  export default DateTimePatterns;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale af.
   */
  let DateTimePatterns_af : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_af' {
  import DateTimePatterns_af = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_af;
  export default DateTimePatterns_af;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale am.
   */
  let DateTimePatterns_am : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_am' {
  import DateTimePatterns_am = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_am;
  export default DateTimePatterns_am;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale ar.
   */
  let DateTimePatterns_ar : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_ar' {
  import DateTimePatterns_ar = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_ar;
  export default DateTimePatterns_ar;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale ar_DZ.
   */
  let DateTimePatterns_ar_DZ : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_ar_DZ' {
  import DateTimePatterns_ar_DZ = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_ar_DZ;
  export default DateTimePatterns_ar_DZ;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale ar_EG.
   */
  let DateTimePatterns_ar_EG : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_ar_EG' {
  import DateTimePatterns_ar_EG = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_ar_EG;
  export default DateTimePatterns_ar_EG;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale az.
   */
  let DateTimePatterns_az : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_az' {
  import DateTimePatterns_az = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_az;
  export default DateTimePatterns_az;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale be.
   */
  let DateTimePatterns_be : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_be' {
  import DateTimePatterns_be = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_be;
  export default DateTimePatterns_be;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale bg.
   */
  let DateTimePatterns_bg : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_bg' {
  import DateTimePatterns_bg = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_bg;
  export default DateTimePatterns_bg;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale bn.
   */
  let DateTimePatterns_bn : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_bn' {
  import DateTimePatterns_bn = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_bn;
  export default DateTimePatterns_bn;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale br.
   */
  let DateTimePatterns_br : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_br' {
  import DateTimePatterns_br = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_br;
  export default DateTimePatterns_br;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale bs.
   */
  let DateTimePatterns_bs : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_bs' {
  import DateTimePatterns_bs = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_bs;
  export default DateTimePatterns_bs;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale ca.
   */
  let DateTimePatterns_ca : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_ca' {
  import DateTimePatterns_ca = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_ca;
  export default DateTimePatterns_ca;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale chr.
   */
  let DateTimePatterns_chr : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_chr' {
  import DateTimePatterns_chr = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_chr;
  export default DateTimePatterns_chr;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale cs.
   */
  let DateTimePatterns_cs : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_cs' {
  import DateTimePatterns_cs = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_cs;
  export default DateTimePatterns_cs;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale cy.
   */
  let DateTimePatterns_cy : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_cy' {
  import DateTimePatterns_cy = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_cy;
  export default DateTimePatterns_cy;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale da.
   */
  let DateTimePatterns_da : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_da' {
  import DateTimePatterns_da = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_da;
  export default DateTimePatterns_da;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale de.
   */
  let DateTimePatterns_de : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_de' {
  import DateTimePatterns_de = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_de;
  export default DateTimePatterns_de;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale de_AT.
   */
  let DateTimePatterns_de_AT : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_de_AT' {
  import DateTimePatterns_de_AT = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_de_AT;
  export default DateTimePatterns_de_AT;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale de_CH.
   */
  let DateTimePatterns_de_CH : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_de_CH' {
  import DateTimePatterns_de_CH = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_de_CH;
  export default DateTimePatterns_de_CH;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale el.
   */
  let DateTimePatterns_el : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_el' {
  import DateTimePatterns_el = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_el;
  export default DateTimePatterns_el;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale en.
   */
  let DateTimePatterns_en : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_en' {
  import DateTimePatterns_en = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_en;
  export default DateTimePatterns_en;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale en_AU.
   */
  let DateTimePatterns_en_AU : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_en_AU' {
  import DateTimePatterns_en_AU = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_en_AU;
  export default DateTimePatterns_en_AU;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale en_CA.
   */
  let DateTimePatterns_en_CA : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_en_CA' {
  import DateTimePatterns_en_CA = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_en_CA;
  export default DateTimePatterns_en_CA;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale en_GB.
   */
  let DateTimePatterns_en_GB : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_en_GB' {
  import DateTimePatterns_en_GB = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_en_GB;
  export default DateTimePatterns_en_GB;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale en_IE.
   */
  let DateTimePatterns_en_IE : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_en_IE' {
  import DateTimePatterns_en_IE = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_en_IE;
  export default DateTimePatterns_en_IE;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale en_IN.
   */
  let DateTimePatterns_en_IN : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_en_IN' {
  import DateTimePatterns_en_IN = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_en_IN;
  export default DateTimePatterns_en_IN;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale en_SG.
   */
  let DateTimePatterns_en_SG : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_en_SG' {
  import DateTimePatterns_en_SG = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_en_SG;
  export default DateTimePatterns_en_SG;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale en_US.
   */
  let DateTimePatterns_en_US : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_en_US' {
  import DateTimePatterns_en_US = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_en_US;
  export default DateTimePatterns_en_US;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale en_ZA.
   */
  let DateTimePatterns_en_ZA : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_en_ZA' {
  import DateTimePatterns_en_ZA = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_en_ZA;
  export default DateTimePatterns_en_ZA;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale es.
   */
  let DateTimePatterns_es : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_es' {
  import DateTimePatterns_es = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_es;
  export default DateTimePatterns_es;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale es_419.
   */
  let DateTimePatterns_es_419 : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_es_419' {
  import DateTimePatterns_es_419 = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_es_419;
  export default DateTimePatterns_es_419;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale es_ES.
   */
  let DateTimePatterns_es_ES : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_es_ES' {
  import DateTimePatterns_es_ES = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_es_ES;
  export default DateTimePatterns_es_ES;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale es_MX.
   */
  let DateTimePatterns_es_MX : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_es_MX' {
  import DateTimePatterns_es_MX = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_es_MX;
  export default DateTimePatterns_es_MX;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale es_US.
   */
  let DateTimePatterns_es_US : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_es_US' {
  import DateTimePatterns_es_US = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_es_US;
  export default DateTimePatterns_es_US;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale et.
   */
  let DateTimePatterns_et : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_et' {
  import DateTimePatterns_et = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_et;
  export default DateTimePatterns_et;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale eu.
   */
  let DateTimePatterns_eu : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_eu' {
  import DateTimePatterns_eu = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_eu;
  export default DateTimePatterns_eu;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale fa.
   */
  let DateTimePatterns_fa : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_fa' {
  import DateTimePatterns_fa = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_fa;
  export default DateTimePatterns_fa;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale fi.
   */
  let DateTimePatterns_fi : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_fi' {
  import DateTimePatterns_fi = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_fi;
  export default DateTimePatterns_fi;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale fil.
   */
  let DateTimePatterns_fil : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_fil' {
  import DateTimePatterns_fil = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_fil;
  export default DateTimePatterns_fil;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale fr.
   */
  let DateTimePatterns_fr : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_fr' {
  import DateTimePatterns_fr = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_fr;
  export default DateTimePatterns_fr;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale fr_CA.
   */
  let DateTimePatterns_fr_CA : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_fr_CA' {
  import DateTimePatterns_fr_CA = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_fr_CA;
  export default DateTimePatterns_fr_CA;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale ga.
   */
  let DateTimePatterns_ga : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_ga' {
  import DateTimePatterns_ga = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_ga;
  export default DateTimePatterns_ga;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale gl.
   */
  let DateTimePatterns_gl : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_gl' {
  import DateTimePatterns_gl = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_gl;
  export default DateTimePatterns_gl;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale gsw.
   */
  let DateTimePatterns_gsw : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_gsw' {
  import DateTimePatterns_gsw = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_gsw;
  export default DateTimePatterns_gsw;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale gu.
   */
  let DateTimePatterns_gu : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_gu' {
  import DateTimePatterns_gu = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_gu;
  export default DateTimePatterns_gu;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale haw.
   */
  let DateTimePatterns_haw : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_haw' {
  import DateTimePatterns_haw = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_haw;
  export default DateTimePatterns_haw;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale he.
   */
  let DateTimePatterns_he : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_he' {
  import DateTimePatterns_he = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_he;
  export default DateTimePatterns_he;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale hi.
   */
  let DateTimePatterns_hi : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_hi' {
  import DateTimePatterns_hi = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_hi;
  export default DateTimePatterns_hi;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale hr.
   */
  let DateTimePatterns_hr : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_hr' {
  import DateTimePatterns_hr = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_hr;
  export default DateTimePatterns_hr;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale hu.
   */
  let DateTimePatterns_hu : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_hu' {
  import DateTimePatterns_hu = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_hu;
  export default DateTimePatterns_hu;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale hy.
   */
  let DateTimePatterns_hy : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_hy' {
  import DateTimePatterns_hy = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_hy;
  export default DateTimePatterns_hy;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale id.
   */
  let DateTimePatterns_id : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_id' {
  import DateTimePatterns_id = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_id;
  export default DateTimePatterns_id;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale in.
   */
  let DateTimePatterns_in : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_in' {
  import DateTimePatterns_in = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_in;
  export default DateTimePatterns_in;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale is.
   */
  let DateTimePatterns_is : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_is' {
  import DateTimePatterns_is = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_is;
  export default DateTimePatterns_is;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale it.
   */
  let DateTimePatterns_it : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_it' {
  import DateTimePatterns_it = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_it;
  export default DateTimePatterns_it;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale iw.
   */
  let DateTimePatterns_iw : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_iw' {
  import DateTimePatterns_iw = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_iw;
  export default DateTimePatterns_iw;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale ja.
   */
  let DateTimePatterns_ja : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_ja' {
  import DateTimePatterns_ja = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_ja;
  export default DateTimePatterns_ja;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale ka.
   */
  let DateTimePatterns_ka : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_ka' {
  import DateTimePatterns_ka = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_ka;
  export default DateTimePatterns_ka;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale kk.
   */
  let DateTimePatterns_kk : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_kk' {
  import DateTimePatterns_kk = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_kk;
  export default DateTimePatterns_kk;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale km.
   */
  let DateTimePatterns_km : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_km' {
  import DateTimePatterns_km = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_km;
  export default DateTimePatterns_km;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale kn.
   */
  let DateTimePatterns_kn : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_kn' {
  import DateTimePatterns_kn = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_kn;
  export default DateTimePatterns_kn;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale ko.
   */
  let DateTimePatterns_ko : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_ko' {
  import DateTimePatterns_ko = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_ko;
  export default DateTimePatterns_ko;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale ky.
   */
  let DateTimePatterns_ky : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_ky' {
  import DateTimePatterns_ky = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_ky;
  export default DateTimePatterns_ky;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale ln.
   */
  let DateTimePatterns_ln : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_ln' {
  import DateTimePatterns_ln = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_ln;
  export default DateTimePatterns_ln;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale lo.
   */
  let DateTimePatterns_lo : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_lo' {
  import DateTimePatterns_lo = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_lo;
  export default DateTimePatterns_lo;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale lt.
   */
  let DateTimePatterns_lt : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_lt' {
  import DateTimePatterns_lt = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_lt;
  export default DateTimePatterns_lt;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale lv.
   */
  let DateTimePatterns_lv : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_lv' {
  import DateTimePatterns_lv = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_lv;
  export default DateTimePatterns_lv;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale mk.
   */
  let DateTimePatterns_mk : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_mk' {
  import DateTimePatterns_mk = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_mk;
  export default DateTimePatterns_mk;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale ml.
   */
  let DateTimePatterns_ml : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_ml' {
  import DateTimePatterns_ml = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_ml;
  export default DateTimePatterns_ml;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale mn.
   */
  let DateTimePatterns_mn : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_mn' {
  import DateTimePatterns_mn = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_mn;
  export default DateTimePatterns_mn;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale mo.
   */
  let DateTimePatterns_mo : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_mo' {
  import DateTimePatterns_mo = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_mo;
  export default DateTimePatterns_mo;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale mr.
   */
  let DateTimePatterns_mr : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_mr' {
  import DateTimePatterns_mr = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_mr;
  export default DateTimePatterns_mr;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale ms.
   */
  let DateTimePatterns_ms : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_ms' {
  import DateTimePatterns_ms = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_ms;
  export default DateTimePatterns_ms;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale mt.
   */
  let DateTimePatterns_mt : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_mt' {
  import DateTimePatterns_mt = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_mt;
  export default DateTimePatterns_mt;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale my.
   */
  let DateTimePatterns_my : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_my' {
  import DateTimePatterns_my = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_my;
  export default DateTimePatterns_my;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale nb.
   */
  let DateTimePatterns_nb : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_nb' {
  import DateTimePatterns_nb = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_nb;
  export default DateTimePatterns_nb;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale ne.
   */
  let DateTimePatterns_ne : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_ne' {
  import DateTimePatterns_ne = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_ne;
  export default DateTimePatterns_ne;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale nl.
   */
  let DateTimePatterns_nl : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_nl' {
  import DateTimePatterns_nl = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_nl;
  export default DateTimePatterns_nl;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale no.
   */
  let DateTimePatterns_no : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_no' {
  import DateTimePatterns_no = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_no;
  export default DateTimePatterns_no;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale no_NO.
   */
  let DateTimePatterns_no_NO : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_no_NO' {
  import DateTimePatterns_no_NO = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_no_NO;
  export default DateTimePatterns_no_NO;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale or.
   */
  let DateTimePatterns_or : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_or' {
  import DateTimePatterns_or = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_or;
  export default DateTimePatterns_or;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale pa.
   */
  let DateTimePatterns_pa : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_pa' {
  import DateTimePatterns_pa = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_pa;
  export default DateTimePatterns_pa;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale pl.
   */
  let DateTimePatterns_pl : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_pl' {
  import DateTimePatterns_pl = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_pl;
  export default DateTimePatterns_pl;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale pt.
   */
  let DateTimePatterns_pt : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_pt' {
  import DateTimePatterns_pt = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_pt;
  export default DateTimePatterns_pt;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale pt_BR.
   */
  let DateTimePatterns_pt_BR : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_pt_BR' {
  import DateTimePatterns_pt_BR = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_pt_BR;
  export default DateTimePatterns_pt_BR;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale pt_PT.
   */
  let DateTimePatterns_pt_PT : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_pt_PT' {
  import DateTimePatterns_pt_PT = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_pt_PT;
  export default DateTimePatterns_pt_PT;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale ro.
   */
  let DateTimePatterns_ro : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_ro' {
  import DateTimePatterns_ro = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_ro;
  export default DateTimePatterns_ro;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale ru.
   */
  let DateTimePatterns_ru : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_ru' {
  import DateTimePatterns_ru = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_ru;
  export default DateTimePatterns_ru;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale sh.
   */
  let DateTimePatterns_sh : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_sh' {
  import DateTimePatterns_sh = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_sh;
  export default DateTimePatterns_sh;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale si.
   */
  let DateTimePatterns_si : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_si' {
  import DateTimePatterns_si = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_si;
  export default DateTimePatterns_si;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale sk.
   */
  let DateTimePatterns_sk : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_sk' {
  import DateTimePatterns_sk = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_sk;
  export default DateTimePatterns_sk;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale sl.
   */
  let DateTimePatterns_sl : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_sl' {
  import DateTimePatterns_sl = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_sl;
  export default DateTimePatterns_sl;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale sq.
   */
  let DateTimePatterns_sq : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_sq' {
  import DateTimePatterns_sq = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_sq;
  export default DateTimePatterns_sq;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale sr.
   */
  let DateTimePatterns_sr : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_sr' {
  import DateTimePatterns_sr = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_sr;
  export default DateTimePatterns_sr;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale sr_Latn.
   */
  let DateTimePatterns_sr_Latn : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_sr_Latn' {
  import DateTimePatterns_sr_Latn = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_sr_Latn;
  export default DateTimePatterns_sr_Latn;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale sv.
   */
  let DateTimePatterns_sv : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_sv' {
  import DateTimePatterns_sv = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_sv;
  export default DateTimePatterns_sv;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale sw.
   */
  let DateTimePatterns_sw : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_sw' {
  import DateTimePatterns_sw = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_sw;
  export default DateTimePatterns_sw;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale ta.
   */
  let DateTimePatterns_ta : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_ta' {
  import DateTimePatterns_ta = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_ta;
  export default DateTimePatterns_ta;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale te.
   */
  let DateTimePatterns_te : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_te' {
  import DateTimePatterns_te = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_te;
  export default DateTimePatterns_te;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale th.
   */
  let DateTimePatterns_th : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_th' {
  import DateTimePatterns_th = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_th;
  export default DateTimePatterns_th;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale tl.
   */
  let DateTimePatterns_tl : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_tl' {
  import DateTimePatterns_tl = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_tl;
  export default DateTimePatterns_tl;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale tr.
   */
  let DateTimePatterns_tr : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_tr' {
  import DateTimePatterns_tr = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_tr;
  export default DateTimePatterns_tr;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale uk.
   */
  let DateTimePatterns_uk : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_uk' {
  import DateTimePatterns_uk = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_uk;
  export default DateTimePatterns_uk;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale ur.
   */
  let DateTimePatterns_ur : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_ur' {
  import DateTimePatterns_ur = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_ur;
  export default DateTimePatterns_ur;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale uz.
   */
  let DateTimePatterns_uz : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_uz' {
  import DateTimePatterns_uz = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_uz;
  export default DateTimePatterns_uz;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale vi.
   */
  let DateTimePatterns_vi : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_vi' {
  import DateTimePatterns_vi = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_vi;
  export default DateTimePatterns_vi;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale zh.
   */
  let DateTimePatterns_zh : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_zh' {
  import DateTimePatterns_zh = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_zh;
  export default DateTimePatterns_zh;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale zh_CN.
   */
  let DateTimePatterns_zh_CN : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_zh_CN' {
  import DateTimePatterns_zh_CN = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_zh_CN;
  export default DateTimePatterns_zh_CN;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale zh_HK.
   */
  let DateTimePatterns_zh_HK : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_zh_HK' {
  import DateTimePatterns_zh_HK = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_zh_HK;
  export default DateTimePatterns_zh_HK;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale zh_TW.
   */
  let DateTimePatterns_zh_TW : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_zh_TW' {
  import DateTimePatterns_zh_TW = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_zh_TW;
  export default DateTimePatterns_zh_TW;
}
// Generated from i18n/datetimepatterns.js
declare namespace ಠ_ಠ.clutz.goog.i18n {
  /**
   * Extended set of localized date/time patterns for locale zu.
   */
  let DateTimePatterns_zu : ಠ_ಠ.clutz.goog.i18n.DateTimePatternsType ;
}
declare module 'goog:goog.i18n.DateTimePatterns_zu' {
  import DateTimePatterns_zu = ಠ_ಠ.clutz.goog.i18n.DateTimePatterns_zu;
  export default DateTimePatterns_zu;
}
