//!! generated by clutz.
// Generated from i18n/durationformat.js
declare namespace ಠ_ಠ.clutz.module$exports$goog$i18n$DurationFormat {
  class DurationFormat {
    private noStructuralTyping_module$exports$goog$i18n$DurationFormat_DurationFormat : any;
    constructor (opt_options ? : ಠ_ಠ.clutz.module$contents$goog$i18n$DurationFormat_DurationFormatOptions , opt_durationSymbols ? : ಠ_ಠ.clutz.module$exports$goog$i18n$DurationSymbolTypes.DurationSymbols ) ;
    durationSymbols_ : ಠ_ಠ.clutz.module$exports$goog$i18n$DurationSymbolTypes.DurationSymbols ;
    /**
     * Formats a string with the amount and correspondent unit.
     * @param durationLike An object for the duration time whose keys can be one of DurationFormatUnit value.
     */
    format (durationLike : ಠ_ಠ.clutz.module$contents$goog$i18n$DurationFormat_DurationLike ) : string ;
  }
  type DurationFormatOptions = { style : ಠ_ಠ.clutz.module$exports$goog$i18n$DurationFormat.DurationFormatStyle } ;
  /**
   * Choices for options bag 'type' in DurationFormat's constructor.
   */
  /**
   * Choices for options bag 'type' in DurationFormat's constructor.
   */
  enum DurationFormatStyle {
    LONG = 1.0 ,
    NARROW = 2.0 ,
    SHORT = 0.0 ,
  }
  /**
   * Available keys for the input object of public method format.
   */
  /**
   * Available keys for the input object of public method format.
   */
  enum DurationFormatUnit {
    DAY = 'days' ,
    HOUR = 'hours' ,
    MINUTE = 'minutes' ,
    MONTH = 'months' ,
    SECOND = 'seconds' ,
    WEEK = 'weeks' ,
    YEAR = 'years' ,
  }
  type DurationLike = { days ? : number , hours ? : number , minutes ? : number , months ? : number , seconds ? : number , weeks ? : number , years ? : number } ;
}
declare module 'goog:goog.i18n.DurationFormat' {
  import DurationFormat = ಠ_ಠ.clutz.module$exports$goog$i18n$DurationFormat;
  export = DurationFormat;
}
// Generated from i18n/durationformat.js
declare namespace ಠ_ಠ.clutz {
  /**
   * Collection of duration unit and time for a locale.
   */
  type module$contents$goog$i18n$DurationFormat_DurationLike = { days ? : number , hours ? : number , minutes ? : number , months ? : number , seconds ? : number , weeks ? : number , years ? : number } ;
}
// Generated from i18n/durationformat.js
declare namespace ಠ_ಠ.clutz {
  /**
   * Collection of duration display style.
   */
  type module$contents$goog$i18n$DurationFormat_DurationFormatOptions = { style : ಠ_ಠ.clutz.module$exports$goog$i18n$DurationFormat.DurationFormatStyle } ;
}
