//!! generated by clutz.
// Generated from i18n/numberformatsymbolstype.js
declare namespace ಠ_ಠ.clutz.module$exports$goog$i18n$NumberFormatSymbolsType {
  /**
   * Number formatting symbols for locale.
   */
  interface Type {
    CURRENCY_PATTERN : string ;
    DECIMAL_PATTERN : string ;
    DECIMAL_SEP : string ;
    DEF_CURRENCY_CODE : string ;
    EXP_SYMBOL : string ;
    GROUP_SEP : string ;
    INFINITY : string ;
    MINUS_SIGN : string ;
    NAN : string ;
    PERCENT : string ;
    PERCENT_PATTERN : string ;
    PERMILL : string ;
    PLUS_SIGN : string ;
    SCIENTIFIC_PATTERN : string ;
    ZERO_DIGIT : string ;
  }
}
declare module 'goog:goog.i18n.NumberFormatSymbolsType' {
  import NumberFormatSymbolsType = ಠ_ಠ.clutz.module$exports$goog$i18n$NumberFormatSymbolsType;
  export = NumberFormatSymbolsType;
}
