//!! generated by clutz.
// Generated from useragent/platform.js
declare namespace ಠ_ಠ.clutz.goog.userAgent.platform {
  /**
   * The version of the platform. We don't determine the version of Linux.
   * For Windows, we only look at the NT version. Non-NT-based versions
   * (e.g. 95, 98, etc.) are given version 0.0.
   */
  let VERSION : string ;
  /**
   * Whether the user agent platform version is higher or the same as the given
   * version.
   * @param version The version to check.
   */
  function isVersion (version : string | number ) : boolean ;
}
declare module 'goog:goog.userAgent.platform' {
  import platform = ಠ_ಠ.clutz.goog.userAgent.platform;
  export = platform;
}
