//!! generated by clutz.
// Generated from useragent/useragenttestutil.js
declare namespace ಠ_ಠ.clutz.goog.userAgentTestUtil {
  /**
   * Return whether a given user agent has been detected.
   * @param agent Value in UserAgents.
   */
  function getUserAgentDetected (agent : string ) : boolean ;
  /**
   * Rerun the initialization code to set all of the goog.userAgent constants.
   */
  function reinitializeUserAgent ( ) : void ;
}
declare module 'goog:goog.userAgentTestUtil' {
  import userAgentTestUtil = ಠ_ಠ.clutz.goog.userAgentTestUtil;
  export = userAgentTestUtil;
}
// Generated from useragent/useragenttestutil.js
declare namespace ಠ_ಠ.clutz.goog.userAgentTestUtil {
  /**
   * Browser definitions.
   */
  /**
   * Browser definitions.
   */
  enum UserAgents {
    EDGE = 'EDGE' ,
    GECKO = 'GECKO' ,
    IE = 'IE' ,
    OPERA = 'OPERA' ,
    WEBKIT = 'WEBKIT' ,
  }
}
declare module 'goog:goog.userAgentTestUtil.UserAgents' {
  import UserAgents = ಠ_ಠ.clutz.goog.userAgentTestUtil.UserAgents;
  export default UserAgents;
}
