//!! generated by clutz.
// Generated from dom/browserrange/geckorange.js
declare namespace ಠ_ಠ.clutz.goog.dom.browserrange {
  /**
   * The constructor for Gecko specific browser ranges.
   */
  class GeckoRange extends ಠ_ಠ.clutz.goog.dom.browserrange.W3cRange {
    private noStructuralTyping_goog_dom_browserrange_GeckoRange : any;
    /**
     * The constructor for Gecko specific browser ranges.
     * @param range The range object.
     */
    constructor (range : Range | null ) ;
    selectInternal (selection ? : any , reversed ? : any ) : void ;
    /**
     * Creates a range object that selects the given node's text.
     * @param node The node to select.
     */
    static createFromNodeContents (node : Node | null ) : ಠ_ಠ.clutz.goog.dom.browserrange.GeckoRange ;
    /**
     * Creates a range object that selects between the given nodes.
     * @param startNode The node to start with.
     * @param startOffset The offset within the node to start.
     * @param endNode The node to end with.
     * @param endOffset The offset within the node to end.
     */
    static createFromNodes (startNode : Node | null , startOffset : number , endNode : Node | null , endOffset : number ) : ಠ_ಠ.clutz.goog.dom.browserrange.GeckoRange ;
  }
}
declare module 'goog:goog.dom.browserrange.GeckoRange' {
  import GeckoRange = ಠ_ಠ.clutz.goog.dom.browserrange.GeckoRange;
  export default GeckoRange;
}
