//!! generated by clutz.
// Generated from testing/mockstorage.js
declare namespace ಠ_ಠ.clutz.goog.testing {
  /**
   * A JS storage instance, implementing the HTML5 Storage interface.
   * See http://www.w3.org/TR/webstorage/ for details.
   */
  class MockStorage implements GlobalStorage {
    private noStructuralTyping_goog_testing_MockStorage : any;
    /**
     * The number of elements in the storage.
     */
    length : number ;
    /**
     * Clears the storage.
     */
    clear ( ) : void ;
    /**
     * Gets an item from the storage.  The item returned is the "structured clone"
     * of the value from setItem.  In practice this means it's the value cast to a
     * string.
     * @param key Storage key.
     */
    getItem (key : string ) : string | null ;
    /**
     * Returns the key at the given index.
     * @param index The index for the key.
     */
    key (index : number ) : string | null ;
    /**
     * Removes and item from the storage.
     * @param key Storage key.
     */
    removeItem (key : string ) : void ;
    /**
     * Sets an item to the storage.
     * @param key Storage key.
     * @param value Storage value. Must be convertible to string.
     */
    setItem (key : string , value : any ) : void ;
  }
}
declare module 'goog:goog.testing.MockStorage' {
  import MockStorage = ಠ_ಠ.clutz.goog.testing.MockStorage;
  export default MockStorage;
}
