//!! generated by clutz.
// Generated from testing/mockrandom.js
declare namespace ಠ_ಠ.clutz.goog.testing {
  /**
   * Class for unit testing code that uses Math.random.
   */
  class MockRandom extends ಠ_ಠ.clutz.goog.Disposable {
    private noStructuralTyping_goog_testing_MockRandom : any;
    /**
     * Class for unit testing code that uses Math.random.
     * @param sequence The sequence of numbers to return. This object will modify this array.
     * @param opt_install Whether to install the MockRandom at construction time.
     */
    constructor (sequence : number [] | null , opt_install ? : boolean ) ;
    disposeInternal ( ) : void ;
    hasMoreValues ( ) : boolean ;
    /**
     * Injects new numbers into the beginning of the sequence.
     * @param values Number or array of numbers to inject.
     */
    inject (values : number [] | number ) : void ;
    install ( ) : void ;
    random ( ) : number ;
    setStrictlyFromSequence (strictlyFromSequence : boolean ) : void ;
    uninstall ( ) : void ;
  }
}
declare module 'goog:goog.testing.MockRandom' {
  import MockRandom = ಠ_ಠ.clutz.goog.testing.MockRandom;
  export default MockRandom;
}
