//!! generated by clutz.
// Generated from testing/mockuseragent.js
declare namespace ಠ_ಠ.clutz.goog.testing {
  /**
   * Class for unit testing code that uses goog.userAgent.
   */
  class MockUserAgent extends ಠ_ಠ.clutz.goog.Disposable {
    private noStructuralTyping_goog_testing_MockUserAgent : any;
    /**
     * Class for unit testing code that uses goog.userAgent.
     */
    constructor ( ) ;
    disposeInternal ( ) : void ;
    getDocumentMode ( ) : number | undefined ;
    getNavigator ( ) : GlobalObject | null ;
    getNavigatorTyped ( ) : Navigator | null ;
    getUserAgentString ( ) : string | null ;
    install ( ) : void ;
    setDocumentMode (documentMode : number ) : void ;
    setNavigator (navigator : GlobalObject | null ) : void ;
    setUserAgentString (userAgent : string ) : void ;
    uninstall ( ) : void ;
  }
}
declare module 'goog:goog.testing.MockUserAgent' {
  import MockUserAgent = ಠ_ಠ.clutz.goog.testing.MockUserAgent;
  export default MockUserAgent;
}
