declare const _default: {
    isElement: boolean;
    isHtmlElement: boolean;
    isHtmlElementOfType: boolean;
    isHtmlAnchorElement: boolean;
    isHtmlButtonElement: boolean;
    isHtmlLinkElement: boolean;
    isHtmlImageElement: boolean;
    isHtmlAudioElement: boolean;
    isHtmlVideoElement: boolean;
    isHtmlInputElement: boolean;
    isHtmlTextAreaElement: boolean;
    isHtmlCanvasElement: boolean;
    isHtmlEmbedElement: boolean;
    isHtmlFormElement: boolean;
    isHtmlFrameElement: boolean;
    isHtmlIFrameElement: boolean;
    isHtmlObjectElement: boolean;
    isHtmlScriptElement: boolean;
};
export default _default;
