//!! generated by clutz.
// Generated from dom/rangeendpoint.js
declare namespace ಠ_ಠ.clutz.goog.dom {
  /**
   * Constants for selection endpoints.
   */
  /**
   * Constants for selection endpoints.
   */
  enum RangeEndpoint {
    END = 0.0 ,
    START = 1.0 ,
  }
}
declare module 'goog:goog.dom.RangeEndpoint' {
  import RangeEndpoint = ಠ_ಠ.clutz.goog.dom.RangeEndpoint;
  export default RangeEndpoint;
}
