//!! generated by clutz.
// Generated from events/pointerfallbackeventtype.js
declare namespace ಠ_ಠ.clutz.goog.events {
  /**
   * Constants for pointer event names that fall back to corresponding mouse event
   * names on unsupported platforms. These are intended to be drop-in replacements
   * for corresponding values in `goog.events.EventType`.
   */
  type PointerFallbackEventType = string &{clutzEnumBrand: never} ;
  let PointerFallbackEventType : {
    POINTERCANCEL : PointerFallbackEventType ,
    POINTERDOWN : PointerFallbackEventType ,
    POINTERENTER : PointerFallbackEventType ,
    POINTERLEAVE : PointerFallbackEventType ,
    POINTERMOVE : PointerFallbackEventType ,
    POINTEROUT : PointerFallbackEventType ,
    POINTEROVER : PointerFallbackEventType ,
    POINTERUP : PointerFallbackEventType ,
  };
}
declare module 'goog:goog.events.PointerFallbackEventType' {
  import PointerFallbackEventType = ಠ_ಠ.clutz.goog.events.PointerFallbackEventType;
  export default PointerFallbackEventType;
}
