//!! generated by clutz.
// Generated from testing/ui/rendererharness.js
declare namespace ಠ_ಠ.clutz.goog.testing.ui {
  /**
   * A driver for testing renderers.
   */
  class RendererHarness extends ಠ_ಠ.clutz.goog.Disposable {
    private noStructuralTyping_goog_testing_ui_RendererHarness : any;
    /**
     * A driver for testing renderers.
     * @param renderer A renderer to test.
     * @param renderParent The parent of the element where controls will be rendered.
     * @param decorateParent The parent of the element where controls will be decorated.
     */
    constructor (renderer : ಠ_ಠ.clutz.goog.ui.ControlRenderer | null , renderParent : GlobalElement | null , decorateParent : GlobalElement | null ) ;
    assertDomMatches ( ) : void ;
    /**
     * Attach a control and decorate the element given in the constructor.
     * @param control A control.
     */
    attachControlAndDecorate (control : ಠ_ಠ.clutz.goog.ui.Control | null ) : GlobalElement | null ;
    /**
     * Attach a control and render its DOM.
     * @param control A control.
     */
    attachControlAndRender (control : ಠ_ಠ.clutz.goog.ui.Control | null ) : GlobalElement | null ;
    /**
     * Destroy the harness, verifying that all assertions had been checked.
     */
    protected disposeInternal ( ) : void ;
  }
}
declare module 'goog:goog.testing.ui.RendererHarness' {
  import RendererHarness = ಠ_ಠ.clutz.goog.testing.ui.RendererHarness;
  export default RendererHarness;
}
