//!! generated by clutz.
// Generated from testing/ui/rendererasserts.js
declare namespace ಠ_ಠ.clutz.goog.testing.ui.rendererasserts {
  function assertNoGetCssClassCallsInConstructor (rendererClassUnderTest : { new ( ) : ಠ_ಠ.clutz.module$exports$goog$ui$ControlRenderer } ) : void ;
}
declare module 'goog:goog.testing.ui.rendererasserts' {
  import rendererasserts = ಠ_ಠ.clutz.goog.testing.ui.rendererasserts;
  export = rendererasserts;
}
