//!! generated by clutz.
// Generated from ui/ac/richinputhandler.js
declare namespace ಠ_ಠ.clutz.goog.ui.ac {
  /**
   * Class for managing the interaction between an autocomplete object and a
   * text-input or textarea.
   */
  class RichInputHandler extends ಠ_ಠ.clutz.goog.ui.ac.InputHandler {
    private noStructuralTyping_goog_ui_ac_RichInputHandler : any;
    /**
     * Class for managing the interaction between an autocomplete object and a
     * text-input or textarea.
     * @param opt_separators Seperators to split multiple entries.
     * @param opt_literals Characters used to delimit text literals.
     * @param opt_multi Whether to allow multiple entries (Default: true).
     * @param opt_throttleTime Number of milliseconds to throttle keyevents with (Default: 150).
     */
    constructor (opt_separators ? : string | null , opt_literals ? : string | null , opt_multi ? : boolean | null , opt_throttleTime ? : number | null ) ;
    /**
     * Selects the given rich row.  The row's select(target) method is called.
     * @param row The row to select.
     */
    selectRow (row : GlobalObject | null ) : boolean ;
  }
}
declare module 'goog:goog.ui.ac.RichInputHandler' {
  import RichInputHandler = ಠ_ಠ.clutz.goog.ui.ac.RichInputHandler;
  export default RichInputHandler;
}
