//!! generated by clutz.
// Generated from ui/bidiinput.js
declare namespace ಠ_ಠ.clutz.goog.ui {
  /**
   * Default implementation of BidiInput.
   */
  class BidiInput extends ಠ_ಠ.clutz.goog.ui.Component {
    private noStructuralTyping_goog_ui_BidiInput : any;
    /**
     * Default implementation of BidiInput.
     * @param opt_domHelper Optional DOM helper.
     */
    constructor (opt_domHelper ? : ಠ_ಠ.clutz.goog.dom.DomHelper | null ) ;
    /**
     * Creates the element for the text input.
     */
    protected createDom ( ) : void ;
    /**
     * Decorates the given HTML element as a BidiInput. The HTML element can be an
     * input element with type='text', a textarea element, or any contenteditable.
     * Overrides {@link goog.ui.Component#decorateInternal}.  Considered protected.
     * @param element Element to decorate.
     */
    protected decorateInternal (element : GlobalElement | null ) : void ;
    disposeInternal ( ) : void ;
    /**
     * Returns the direction of the input element.
     */
    getDirection ( ) : string | null ;
    getElement ( ) : HTMLInputElement | null ;
    /**
     * Returns the value of the underlying input field.
     */
    getValue ( ) : string ;
    /**
     * Sets the value of the underlying input field, and sets the direction
     * according to the given value.
     * @param value The Value to set in the underlying input field.
     */
    setValue (value : string ) : void ;
  }
}
declare module 'goog:goog.ui.BidiInput' {
  import BidiInput = ಠ_ಠ.clutz.goog.ui.BidiInput;
  export default BidiInput;
}
