//!! generated by clutz.
// Generated from ui/cookieeditor.js
declare namespace ಠ_ಠ.clutz.goog.ui {
  /**
   * Displays and edits the value of a cookie.
   */
  class CookieEditor extends ಠ_ಠ.clutz.goog.ui.Component {
    private noStructuralTyping_goog_ui_CookieEditor : any;
    constructor (opt_domHelper ? : ಠ_ಠ.clutz.goog.dom.DomHelper | null ) ;
    canDecorate ( ) : any ;
    createDom ( ) : void ;
    disposeInternal ( ) : void ;
    enterDocument ( ) : void ;
    /**
     * Sets the cookie which this component will edit.
     * @param cookieKey Cookie key.
     */
    selectCookie (cookieKey : string ) : void ;
  }
}
declare module 'goog:goog.ui.CookieEditor' {
  import CookieEditor = ಠ_ಠ.clutz.goog.ui.CookieEditor;
  export default CookieEditor;
}
