//!! generated by clutz.
// Generated from ui/menubase.js
declare namespace ಠ_ಠ.clutz.goog.ui {
  /**
   * The MenuBase class provides an abstract base class for different
   * implementations of menu controls.
   */
  class MenuBase extends ಠ_ಠ.clutz.goog.ui.Popup {
    private noStructuralTyping_goog_ui_MenuBase : any;
    /**
     * The MenuBase class provides an abstract base class for different
     * implementations of menu controls.
     * @param opt_element A DOM element for the popup.
     */
    constructor (opt_element ? : GlobalElement | null ) ;
    disposeInternal ( ) : void ;
    /**
     * Returns the selected item
     */
    getSelectedItem ( ) : GlobalObject | null ;
    /**
     * Called after the menu is hidden. Derived classes can override to hook this
     * event but should make sure to call the parent class method.
     * @param opt_target Target of the event causing the hide.
     */
    protected onHide (opt_target ? : Node | null ) : void ;
    /**
     * Key down handler for the menu. Derived classes should override.
     * @param e The event object.
     */
    protected onKeyDown (e : ಠ_ಠ.clutz.goog.events.KeyEvent | null ) : void ;
    /**
     * Mouse down handler for the menu. Derived classes should override.
     * @param e The event object.
     */
    protected onMouseDown (e : ಠ_ಠ.clutz.goog.events.Event ) : void ;
    /**
     * Mouse out handler for the menu. Derived classes should override.
     * @param e The event object.
     */
    protected onMouseOut (e : ಠ_ಠ.clutz.goog.events.Event | null ) : void ;
    /**
     * Mouse over handler for the menu. Derived classes should override.
     * @param e The event object.
     */
    protected onMouseOver (e : ಠ_ಠ.clutz.goog.events.Event | null ) : void ;
    /**
     * Mouse up handler for the menu. Derived classes should override.
     * @param e The event object.
     */
    protected onMouseUp (e : ಠ_ಠ.clutz.goog.events.Event | null ) : void ;
    /**
     * Called after the menu is shown. Derived classes can override to hook this
     * event but should make sure to call the parent class method.
     */
    protected onShow ( ) : void ;
    /**
     * Sets the selected item
     * @param item The item to select. The type of this item is specific to the menu class.
     */
    setSelectedItem (item : GlobalObject | null ) : void ;
    /**
     * Events fired by the Menu
     */
    static Events : { ITEM_ACTION : string } ;
  }
}
declare module 'goog:goog.ui.MenuBase' {
  import MenuBase = ಠ_ಠ.clutz.goog.ui.MenuBase;
  export default MenuBase;
}
