//!! generated by clutz.
// Generated from ui/menuheaderrenderer.js
declare namespace ಠ_ಠ.clutz.goog.ui {
  /**
   * Renderer for menu headers.
   */
  class MenuHeaderRenderer extends ಠ_ಠ.clutz.goog.ui.ControlRenderer {
    private noStructuralTyping_goog_ui_MenuHeaderRenderer : any;
    /**
     * Renderer for menu headers.
     */
    constructor ( ) ;
    /**
     * Returns the CSS class to be applied to the root element of components
     * rendered using this renderer.
     */
    getCssClass ( ) : string ;
    /**
     * Default CSS class to be applied to the root element of components rendered
     * by this renderer.
     */
    static CSS_CLASS : string ;
    static getInstance ( ) : ಠ_ಠ.clutz.goog.ui.MenuHeaderRenderer ;
    static instance_ : ಠ_ಠ.clutz.goog.ui.MenuHeaderRenderer ;
  }
}
declare module 'goog:goog.ui.MenuHeaderRenderer' {
  import MenuHeaderRenderer = ಠ_ಠ.clutz.goog.ui.MenuHeaderRenderer;
  export default MenuHeaderRenderer;
}
