//!! generated by clutz.
// Generated from ui/tabbarrenderer.js
declare namespace ಠ_ಠ.clutz.goog.ui {
  /**
   * Default renderer for {@link goog.ui.TabBar}s, based on the `TabPane`
   * code.  The tab bar's DOM structure is determined by its orientation and
   * location relative to tab contents.  For example, a horizontal tab bar
   * located above tab contents looks like this:
   *
   * <div class="goog-tab-bar goog-tab-bar-horizontal goog-tab-bar-top">
   * ...(tabs here)...
   * </div>
   */
  class TabBarRenderer extends ಠ_ಠ.clutz.goog.ui.ContainerRenderer {
    private noStructuralTyping_goog_ui_TabBarRenderer : any;
    /**
     * Default renderer for {@link goog.ui.TabBar}s, based on the `TabPane`
     * code.  The tab bar's DOM structure is determined by its orientation and
     * location relative to tab contents.  For example, a horizontal tab bar
     * located above tab contents looks like this:
     *
     * <div class="goog-tab-bar goog-tab-bar-horizontal goog-tab-bar-top">
     * ...(tabs here)...
     * </div>
     */
    constructor ( ) ;
    /**
     * Returns all CSS class names applicable to the tab bar, based on its state.
     * Overrides the superclass implementation by appending the location-specific
     * class name to the list.
     * @param tabBar Tab bar whose CSS classes are to be returned.
     */
    getClassNames (tabBar : ಠ_ಠ.clutz.goog.ui.Container | null ) : string [] ;
    /**
     * Returns the CSS class name to be applied to the root element of all tab bars
     * rendered or decorated using this renderer.
     */
    getCssClass ( ) : string ;
    /**
     * Sets the tab bar's state based on the given CSS class name, encountered
     * during decoration.  Overrides the superclass implementation by recognizing
     * class names representing tab bar orientation and location.
     * @param tabBar Tab bar to configure.
     * @param className CSS class name.
     * @param baseClass Base class name used as the root of state-specific class names (typically the renderer's own class name).
     */
    protected setStateFromClassName (tabBar : ಠ_ಠ.clutz.goog.ui.Container | null , className : string , baseClass : string ) : void ;
    /**
     * Default CSS class to be applied to the root element of components rendered
     * by this renderer.
     */
    static CSS_CLASS : string ;
    static getInstance ( ) : ಠ_ಠ.clutz.goog.ui.TabBarRenderer ;
    static instance_ : ಠ_ಠ.clutz.goog.ui.TabBarRenderer ;
  }
}
declare module 'goog:goog.ui.TabBarRenderer' {
  import TabBarRenderer = ಠ_ಠ.clutz.goog.ui.TabBarRenderer;
  export default TabBarRenderer;
}
