//!! generated by clutz.
// Generated from ui/toolbarseparator.js
declare namespace ಠ_ಠ.clutz.goog.ui {
  /**
   * A separator control for a toolbar.
   */
  class ToolbarSeparator extends ಠ_ಠ.clutz.goog.ui.Separator {
    private noStructuralTyping_goog_ui_ToolbarSeparator : any;
    /**
     * A separator control for a toolbar.
     * @param opt_renderer Renderer to render or decorate the separator; defaults to {@link goog.ui.ToolbarSeparatorRenderer}.
     * @param opt_domHelper Optional DOM helper, used for document interaction.
     */
    constructor (opt_renderer ? : ಠ_ಠ.clutz.goog.ui.ToolbarSeparatorRenderer | null , opt_domHelper ? : ಠ_ಠ.clutz.goog.dom.DomHelper | null ) ;
  }
}
declare module 'goog:goog.ui.ToolbarSeparator' {
  import ToolbarSeparator = ಠ_ಠ.clutz.goog.ui.ToolbarSeparator;
  export default ToolbarSeparator;
}
