load("//closure/goog:defs.bzl", "js_library")

package(default_visibility = ["//visibility:public"])

js_library(
    name = "nodejs",
    srcs = ["nodejs.js", "nodejs.d.ts"],
    lenient = True,
)

js_library(
    name = "webworkers",
    srcs = ["webworkers.js", "webworkers.d.ts"],
    lenient = True,
)
