load("@io_bazel_rules_closure//closure:defs.bzl", "closure_js_library")

package(default_visibility = ["//visibility:public"])

closure_js_library(
    name = "nodejs",
    srcs = ["nodejs.js", "nodejs.clutz.d.ts"],
    lenient = True,
)

closure_js_library(
    name = "webworkers",
    srcs = ["webworkers.js", "webworkers.clutz.d.ts"],
    lenient = True,
)
