//!! generated by clutz.
// Generated from locale/countries.js
declare namespace ಠ_ಠ.clutz.goog.locale {
  /**
   * List of codes for countries valid today.
   */
  let countries : string [] ;
}
declare module 'goog:goog.locale.countries' {
  import countries = ಠ_ಠ.clutz.goog.locale.countries;
  export default countries;
}
