//!! generated by clutz.
// Generated from locale/nativenameconstants.js
declare namespace ಠ_ಠ.clutz.goog.locale {
  /**
   * Native country and language names
   */
  let nativeNameConstants : { [ key: string ]: { [ key: string ]: string } } ;
}
declare module 'goog:goog.locale.nativeNameConstants' {
  import nativeNameConstants = ಠ_ಠ.clutz.goog.locale.nativeNameConstants;
  export default nativeNameConstants;
}
