//!! generated by clutz.
// Generated from ui/emoji/emojipaletterenderer.js
declare namespace ಠ_ಠ.clutz.goog.ui.emoji {
  /**
   * Renders an emoji palette.
   */
  class EmojiPaletteRenderer extends ಠ_ಠ.clutz.goog.ui.PaletteRenderer {
    private noStructuralTyping_goog_ui_emoji_EmojiPaletteRenderer : any;
    /**
     * Renders an emoji palette.
     * @param defaultImgUrl Url of the img that should be used to fill up the cells in the emoji table, to prevent jittering. Will be stretched to the emoji cell size. A good image is a transparent dot.
     */
    constructor (defaultImgUrl : string | null ) ;
    /**
     * Builds the inner contents of a palette item out of sprite metadata.
     * @param dom DOM helper for constructing DOM elements.
     * @param spriteInfo The metadata to create the css for the sprite.
     * @param displayUrl The URL of the image for this cell.
     */
    buildElementFromSpriteMetadata (dom : ಠ_ಠ.clutz.goog.dom.DomHelper | null , spriteInfo : ಠ_ಠ.clutz.goog.ui.emoji.SpriteInfo | null , displayUrl : string ) : HTMLDivElement ;
    createCell (node ? : any , dom ? : any ) : any ;
    /**
     * Creates a palette item from the given emoji data.
     * @param dom DOM helper for constructing DOM elements.
     * @param id Goomoji id for the emoji.
     * @param spriteInfo Spriting info for the emoji.
     * @param displayUrl URL of the image served for this cell, whether an individual emoji image or a sprite.
     */
    createPaletteItem (dom : ಠ_ಠ.clutz.goog.dom.DomHelper | null , id : string , spriteInfo : ಠ_ಠ.clutz.goog.ui.emoji.SpriteInfo | null , displayUrl : string ) : HTMLDivElement ;
    /**
     * Returns the item corresponding to the given node, or null if the node is
     * neither a palette cell nor part of a palette item.
     * @param palette Palette in which to look for the item.
     * @param node Node to look for.
     */
    getContainingItem (palette : ಠ_ಠ.clutz.goog.ui.Palette | null , node : Node | null ) : Node | null ;
    /**
     * Modifies a palette item containing an animated emoji, in response to the
     * animated emoji being successfully downloaded.
     * @param item The palette item to update.
     * @param animatedImg An Image object containing the animated emoji.
     */
    updateAnimatedPaletteItem (item : GlobalElement | null , animatedImg : Image | null ) : void ;
    static getCssClass ( ) : any ;
  }
}
declare module 'goog:goog.ui.emoji.EmojiPaletteRenderer' {
  import EmojiPaletteRenderer = ಠ_ಠ.clutz.goog.ui.emoji.EmojiPaletteRenderer;
  export default EmojiPaletteRenderer;
}
