//!! generated by clutz.
// Generated from ui/emoji/emojipalette.js
declare namespace ಠ_ಠ.clutz.goog.ui.emoji {
  /**
   * A page of emoji to be displayed in an EmojiPicker.
   */
  class EmojiPalette extends ಠ_ಠ.clutz.goog.ui.Palette {
    private noStructuralTyping_goog_ui_emoji_EmojiPalette : any;
    /**
     * A page of emoji to be displayed in an EmojiPicker.
     * @param emoji List of emoji for this page.
     * @param opt_urlPrefix Prefix that should be prepended to all URL.
     * @param opt_renderer Renderer used to render or decorate the palette; defaults to {@link goog.ui.PaletteRenderer}.
     * @param opt_domHelper Optional DOM helper.
     */
    constructor (emoji : ( any [] | null ) [] | null , opt_urlPrefix ? : string | null , opt_renderer ? : ಠ_ಠ.clutz.goog.ui.PaletteRenderer | null , opt_domHelper ? : ಠ_ಠ.clutz.goog.dom.DomHelper | null ) ;
    disposeInternal ( ) : void ;
    /**
     * Returns the index of the specified emoji within this palette.
     * @param id Id of the emoji to look up.
     */
    getEmojiIndex (id : string ) : number ;
    /**
     * Returns the image loader that this palette uses. Used for testing.
     */
    getImageLoader ( ) : ಠ_ಠ.clutz.goog.net.ImageLoader | null ;
    getNumberOfEmoji ( ) : number ;
    getSelectedEmoji ( ) : ಠ_ಠ.clutz.goog.ui.emoji.Emoji | null ;
    loadAnimatedEmoji ( ) : void ;
  }
}
declare module 'goog:goog.ui.emoji.EmojiPalette' {
  import EmojiPalette = ಠ_ಠ.clutz.goog.ui.emoji.EmojiPalette;
  export default EmojiPalette;
}
