load("@io_bazel_rules_closure//closure:defs.bzl", "closure_js_library")

package(default_visibility = ["//visibility:public"])

licenses(["notice"])

closure_js_library(
    name = "jsloader_test1",
    testonly = 1,
    srcs = ["jsloader_test1.js", "jsloader_test1.clutz.d.ts"],
    lenient = True,
)

closure_js_library(
    name = "jsloader_test2",
    testonly = 1,
    srcs = ["jsloader_test2.js", "jsloader_test2.clutz.d.ts"],
    lenient = True,
)

closure_js_library(
    name = "jsloader_test3",
    testonly = 1,
    srcs = ["jsloader_test3.js", "jsloader_test3.clutz.d.ts"],
    lenient = True,
)

closure_js_library(
    name = "jsloader_test4",
    testonly = 1,
    srcs = ["jsloader_test4.js", "jsloader_test4.clutz.d.ts"],
    lenient = True,
)
