load("@rules_derivita_ts//js:index.bzl", "js_library")

package(default_visibility = ["//visibility:public"])

licenses(["notice"])

js_library(
    name = "jsloader_test1",
    testonly = 1,
    srcs = ["jsloader_test1.js", "jsloader_test1.d.ts"],
    lenient = True,
)

js_library(
    name = "jsloader_test2",
    testonly = 1,
    srcs = ["jsloader_test2.js", "jsloader_test2.d.ts"],
    lenient = True,
)

js_library(
    name = "jsloader_test3",
    testonly = 1,
    srcs = ["jsloader_test3.js", "jsloader_test3.d.ts"],
    lenient = True,
)

js_library(
    name = "jsloader_test4",
    testonly = 1,
    srcs = ["jsloader_test4.js", "jsloader_test4.d.ts"],
    lenient = True,
)
