load("@rules_derivita_ts//js:index.bzl", "js_library")

package(default_visibility = ["//visibility:public"])

licenses(["notice"])

js_library(
    name = "webgl",
    srcs = ["webgl.js", "webgl.d.ts"],
    lenient = True,
)
