//!! generated by clutz.
// Generated from editor/plugins/undoredostate.js
declare namespace ಠ_ಠ.clutz.goog.editor.plugins {
  /**
   * Represents an undo and redo action for a particular state transition.
   */
  class UndoRedoState extends ಠ_ಠ.clutz.goog.events.EventTarget {
    private noStructuralTyping_goog_editor_plugins_UndoRedoState : any;
    /**
     * Represents an undo and redo action for a particular state transition.
     * @param asynchronous Whether the undo or redo actions for this state complete asynchronously. If true, then this state must fire an ACTION_COMPLETED event when undo or redo is complete.
     */
    constructor (asynchronous : boolean ) ;
    /**
     * Checks if two undo-redo states are the same.
     * @param state The state to compare.
     */
    equals (a : ಠ_ಠ.clutz.goog.editor.plugins.UndoRedoState | null ) : boolean ;
    isAsynchronous ( ) : boolean ;
    redo ( ...a : any [] ) : any ;
    undo ( ...a : any [] ) : any ;
    static ACTION_COMPLETED : string ;
  }
}
declare module 'goog:goog.editor.plugins.UndoRedoState' {
  import UndoRedoState = ಠ_ಠ.clutz.goog.editor.plugins.UndoRedoState;
  export default UndoRedoState;
}
