//!! generated by clutz.
// Generated from fs/url.js
declare namespace ಠ_ಠ.clutz.goog.fs.url {
  /**
   * Checks whether this browser supports Object Urls. If not, calls to
   * createObjectUrl and revokeObjectUrl will result in an error.
   */
  function browserSupportsObjectUrls ( ) : boolean ;
  /**
   * Creates a blob URL for a blob object.
   * Throws an error if the browser does not support Object Urls.
   * @param obj The object for which to create the URL.
   */
  function createObjectUrl (obj : File | Blob | MediaSource | MediaStream ) : string ;
  /**
   * Revokes a URL created by {@link goog.fs.url.createObjectUrl}.
   * Throws an error if the browser does not support Object Urls.
   * @param url The URL to revoke.
   */
  function revokeObjectUrl (url : string ) : void ;
}
declare module 'goog:goog.fs.url' {
  import url = ಠ_ಠ.clutz.goog.fs.url;
  export = url;
}
