//!! generated by clutz.
// Generated from html/sanitizer/csspropertysanitizer.js
declare namespace ಠ_ಠ.clutz.goog.html.sanitizer.CssPropertySanitizer {
  /**
   * Sanitizes the value for a given a browser-parsed CSS value.
   * @param propName A property name.
   * @param propValue Value of the property as parsed by the browser.
   * @param opt_uriRewriter A URI rewriter that returns an unwrapped goog.html.SafeUrl.
   */
  function sanitizeProperty (propName : string , propValue : string , opt_uriRewriter ? : (a : string , b : string ) => ಠ_ಠ.clutz.module$exports$goog$html$SafeUrl | null ) : string | null ;
}
declare module 'goog:goog.html.sanitizer.CssPropertySanitizer' {
  import CssPropertySanitizer = ಠ_ಠ.clutz.goog.html.sanitizer.CssPropertySanitizer;
  export = CssPropertySanitizer;
}
