export declare const global: typeof globalThis;
export declare const require: typeof goog.require;
export declare const define: typeof goog.define;
export declare const DEBUG: boolean;
export declare const LOCALE: string;
export declare const TRUSTED_SITE: boolean;
export declare const DISALLOW_TEST_ONLY_CODE: boolean;
export declare const getGoogModule: typeof goog.module.get;
export declare const setTestOnly: typeof goog.setTestOnly;
export declare const forwardDeclare: typeof goog.forwardDeclare;
export declare const getObjectByName: typeof goog.getObjectByName;
export declare const basePath: string;
export declare const addSingletonGetter: typeof goog.addSingletonGetter;
export declare const typeOf: typeof goog.typeOf;
export declare const isArrayLike: typeof goog.isArrayLike;
export declare const isDateLike: typeof goog.isDateLike;
export declare const isObject: typeof goog.isObject;
export declare const getUid: typeof goog.getUid;
export declare const hasUid: typeof goog.hasUid;
export declare const removeUid: typeof goog.removeUid;
export declare const now: () => number;
export declare const globalEval: typeof goog.globalEval;
export declare const getCssName: typeof goog.getCssName;
export declare const setCssNameMapping: typeof goog.setCssNameMapping;
export declare const getMsg: typeof goog.getMsg;
export declare const getMsgWithFallback: typeof goog.getMsgWithFallback;
export declare const exportSymbol: typeof goog.exportSymbol;
export declare const exportProperty: typeof goog.exportProperty;
export declare const abstractMethod: typeof goog.abstractMethod;
export declare const cloneObject: typeof goog.cloneObject;
export declare const bind: typeof goog.bind;
export declare const partial: typeof goog.partial;
export declare const inherits: typeof goog.inherits;
export declare const scope: typeof goog.scope;
export declare const defineClass: typeof goog.defineClass;
export declare const declareModuleId: typeof goog.declareModuleId;
export declare const module: {
    get: typeof goog.module.get;
};
