//!! generated by clutz.
// Generated from test_module.js
declare namespace ಠ_ಠ.clutz.goog {
  export import test_module = ಠ_ಠ.clutz.module$contents$goog$test_module_test ;
}
declare module 'goog:goog.test_module' {
  import test_module = ಠ_ಠ.clutz.goog.test_module;
  export default test_module;
}
// Generated from test_module.js
declare namespace ಠ_ಠ.clutz {
  class module$contents$goog$test_module_test {
    private noStructuralTyping_module$contents$goog$test_module_test : any;
    static CLOSING_SCRIPT_TAG : string ;
  }
}
declare namespace ಠ_ಠ.clutz {
  export import module$exports$goog$test_module = ಠ_ಠ.clutz.module$contents$goog$test_module_test ;
}
