//!! generated by clutz.
// Generated from net/bulkloaderhelper.js
declare namespace ಠ_ಠ.clutz.goog.net {
  /**
   * Helper class used to load multiple URIs.
   */
  class BulkLoaderHelper extends ಠ_ಠ.clutz.goog.Disposable {
    private noStructuralTyping_goog_net_BulkLoaderHelper : any;
    /**
     * Helper class used to load multiple URIs.
     * @param uris The URIs to load.
     */
    constructor (uris : ( string | ಠ_ಠ.clutz.goog.Uri | null ) [] | null ) ;
    disposeInternal ( ) : void ;
    /**
     * Gets the response texts.
     */
    getResponseTexts ( ) : string [] | null ;
    /**
     * Gets the URI by id.
     * @param id The id.
     */
    getUri (id : number ) : string | ಠ_ಠ.clutz.goog.Uri | null ;
    /**
     * Gets the URIs.
     */
    getUris ( ) : ( string | ಠ_ಠ.clutz.goog.Uri | null ) [] | null ;
    /**
     * Determines if the load of the URIs is complete.
     */
    isLoadComplete ( ) : boolean ;
    /**
     * Sets the response text by id.
     * @param id The id.
     * @param responseText The response texts.
     */
    setResponseText (id : number , responseText : string ) : void ;
  }
}
declare module 'goog:goog.net.BulkLoaderHelper' {
  import BulkLoaderHelper = ಠ_ಠ.clutz.goog.net.BulkLoaderHelper;
  export default BulkLoaderHelper;
}
