load("@rules_derivita_ts//js:index.bzl", "js_library")

package(default_visibility = ["//visibility:public"])

licenses(["notice"])

js_library(
    name = "array",
    srcs = ["array.js", "array.d.ts"],
    lenient = True,
    deps = ["//closure/goog/asserts"],
)
