//!! generated by clutz.
// Generated from proto2/fielddescriptor.js
declare namespace ಠ_ಠ.clutz.goog.proto2 {
  /**
   * A class which describes a field in a Protocol Buffer 2 Message.
   */
  class FieldDescriptor {
    private noStructuralTyping_goog_proto2_FieldDescriptor : any;
    /**
     * A class which describes a field in a Protocol Buffer 2 Message.
     * @param messageType Constructor for the message class to which the field described by this class belongs.
     * @param tag The field's tag index.
     * @param metadata The metadata about this field that will be used to construct this descriptor.
     */
    constructor (messageType : { new ( ) : ಠ_ಠ.clutz.goog.proto2.Message } , tag : number | string , metadata : { defaultValue ? : any , fieldType : ಠ_ಠ.clutz.goog.proto2.FieldDescriptor.FieldType , name : string , packed ? : any , repeated ? : any , required ? : any , type : Function } ) ;
    /**
     * Returns true if simple conversions between numbers and strings are permitted
     * during deserialization for this field.
     */
    deserializationConversionPermitted ( ) : boolean ;
    /**
     * Returns the descriptor describing the message that defined this field.
     */
    getContainingType ( ) : ಠ_ಠ.clutz.goog.proto2.Descriptor ;
    /**
     * Returns the default value of this field.
     */
    getDefaultValue ( ) : any ;
    /**
     * Returns the descriptor of the message type of this field. Only valid
     * for fields of type GROUP and MESSAGE.
     */
    getFieldMessageType ( ) : ಠ_ಠ.clutz.goog.proto2.Descriptor ;
    /**
     * Returns the field type of the field described by this descriptor.
     */
    getFieldType ( ) : ಠ_ಠ.clutz.goog.proto2.FieldDescriptor.FieldType ;
    /**
     * Returns the name of the field that this descriptor represents.
     */
    getName ( ) : string ;
    /**
     * Returns the native (i.e. ECMAScript) type of the field described by this
     * descriptor.
     */
    getNativeType ( ) : GlobalObject | null ;
    /**
     * Returns the tag of the field that this descriptor represents.
     */
    getTag ( ) : number ;
    isCompositeType ( ) : boolean ;
    /**
     * Returns whether the field described by this descriptor is optional.
     */
    isOptional ( ) : boolean ;
    /**
     * Returns whether the field described by this descriptor is packed.
     */
    isPacked ( ) : boolean ;
    /**
     * Returns whether the field described by this descriptor is repeating.
     */
    isRepeated ( ) : boolean ;
    /**
     * Returns whether the field described by this descriptor is required.
     */
    isRequired ( ) : boolean ;
  }
}
// Generated from proto2/fielddescriptor.js
declare namespace ಠ_ಠ.clutz.goog.proto2.FieldDescriptor {
  /**
   * An enumeration defining the possible field types.
   * Should be a mirror of that defined in descriptor.h.
   */
  enum FieldType {
    BOOL = 8.0 ,
    BYTES = 12.0 ,
    DOUBLE = 1.0 ,
    ENUM = 14.0 ,
    FIXED32 = 7.0 ,
    FIXED64 = 6.0 ,
    FLOAT = 2.0 ,
    GROUP = 10.0 ,
    INT32 = 5.0 ,
    INT64 = 3.0 ,
    MESSAGE = 11.0 ,
    SFIXED32 = 15.0 ,
    SFIXED64 = 16.0 ,
    SINT32 = 17.0 ,
    SINT64 = 18.0 ,
    STRING = 9.0 ,
    UINT32 = 13.0 ,
    UINT64 = 4.0 ,
  }
}
declare module 'goog:goog.proto2.FieldDescriptor' {
  import FieldDescriptor = ಠ_ಠ.clutz.goog.proto2.FieldDescriptor;
  export default FieldDescriptor;
}
