//!! generated by clutz.
// Generated from proto2/lazydeserializer.js
declare namespace ಠ_ಠ.clutz.goog.proto2 {
  /**
   * Base class for all lazy deserializers.
   */
  class LazyDeserializer extends ಠ_ಠ.clutz.goog.proto2.Serializer {
    private noStructuralTyping_goog_proto2_LazyDeserializer : any;
    /**
     * Base class for all lazy deserializers.
     */
    constructor ( ) ;
    deserialize (descriptor ? : any , data ? : any ) : any ;
    /**
     * Deserializes a message field from the expected format and places the
     * data in the given message
     * @param message The message in which to place the information.
     * @param field The field for which to set the message value.
     * @param data The serialized data for the field.
     */
    deserializeField (a : ಠ_ಠ.clutz.goog.proto2.Message | null , b : ಠ_ಠ.clutz.goog.proto2.FieldDescriptor | null , c : any ) : any ;
    deserializeTo (message ? : any , data ? : any ) : any ;
  }
}
declare module 'goog:goog.proto2.LazyDeserializer' {
  import LazyDeserializer = ಠ_ಠ.clutz.goog.proto2.LazyDeserializer;
  export default LazyDeserializer;
}
