//!! generated by clutz.
// Generated from proto2/pbliteserializer.js
declare namespace ಠ_ಠ.clutz.goog.proto2 {
  /**
   * PB-Lite serializer.
   */
  class PbLiteSerializer extends ಠ_ಠ.clutz.goog.proto2.LazyDeserializer {
    private noStructuralTyping_goog_proto2_PbLiteSerializer : any;
    /**
     * PB-Lite serializer.
     */
    constructor ( ) ;
    deserialize (descriptor ? : any , data ? : any ) : any ;
    deserializeField (message ? : any , field ? : any , value ? : any ) : any ;
    getDeserializedValue (field ? : any , value ? : any ) : any ;
    getSerializedValue (field ? : any , value ? : any ) : any ;
    /**
     * Serializes a message to a PB-Lite object.
     * @param message The message to be serialized.
     */
    serialize (message : ಠ_ಠ.clutz.goog.proto2.Message | null ) : any [] ;
    /**
     * By default, the proto tag with id 1 will have index 1 in the serialized
     * array.
     *
     * If the serializer is set to use zero-indexing, the tag with id 1 will have
     * index 0.
     * @param zeroIndexing Whether this serializer should deal with 0-indexed protos.
     */
    setZeroIndexed (zeroIndexing : boolean ) : void ;
  }
}
declare module 'goog:goog.proto2.PbLiteSerializer' {
  import PbLiteSerializer = ಠ_ಠ.clutz.goog.proto2.PbLiteSerializer;
  export default PbLiteSerializer;
}
