//!! generated by clutz.
// Generated from history/eventtype.js
declare namespace ಠ_ಠ.clutz.goog.history {
  /**
   * Event types for goog.history.
   */
  /**
   * Event types for goog.history.
   */
  enum EventType {
    NAVIGATE = 'navigate' ,
  }
}
declare module 'goog:goog.history.EventType' {
  import EventType = ಠ_ಠ.clutz.goog.history.EventType;
  export default EventType;
}
