load("@rules_derivita_ts//js:index.bzl", "js_library")

package(default_visibility = ["//visibility:public"])

licenses(["notice"])

js_library(
    name = "reflect",
    srcs = ["reflect.js", "reflect.d.ts"],
    lenient = True,
)
