load("//closure/goog:defs.bzl", "js_library")

package(default_visibility = ["//visibility:public"])

licenses(["notice"])

js_library(
    name = "delegateregistry",
    srcs = ["delegateregistry.js", "delegateregistry.d.ts"],
    lenient = True,
    deps = [
        "//closure/goog/array",
        "//closure/goog/asserts",
        "//closure/goog/debug",
    ],
)

js_library(
    name = "delegates",
    srcs = ["delegates.js", "delegates.d.ts"],
    lenient = True,
)
