declare const _default: {
    assertIsElement: Element;
    assertIsHtmlElement: HTMLElement;
    assertIsHtmlElementOfType: any;
    assertIsHtmlAnchorElement: HTMLAnchorElement;
    assertIsHtmlButtonElement: HTMLButtonElement;
    assertIsHtmlLinkElement: HTMLLinkElement;
    assertIsHtmlImageElement: HTMLImageElement;
    assertIsHtmlAudioElement: HTMLAudioElement;
    assertIsHtmlVideoElement: HTMLVideoElement;
    assertIsHtmlInputElement: HTMLInputElement;
    assertIsHtmlTextAreaElement: HTMLTextAreaElement;
    assertIsHtmlCanvasElement: HTMLCanvasElement;
    assertIsHtmlEmbedElement: HTMLEmbedElement;
    assertIsHtmlFormElement: HTMLFormElement;
    assertIsHtmlFrameElement: HTMLFrameElement;
    assertIsHtmlIFrameElement: HTMLIFrameElement;
    assertIsHtmlObjectElement: HTMLObjectElement;
    assertIsHtmlScriptElement: HTMLScriptElement;
};
export default _default;
