//!! generated by clutz.
// Generated from asserts/dom.js
declare namespace ಠ_ಠ.clutz.goog.asserts.dom {
  function assertIsElement (value : any ) : GlobalElement ;
  function assertIsHtmlAnchorElement (value : any ) : HTMLAnchorElement ;
  function assertIsHtmlAudioElement (value : any ) : HTMLAudioElement ;
  function assertIsHtmlButtonElement (value : any ) : HTMLButtonElement ;
  function assertIsHtmlCanvasElement (value : any ) : HTMLCanvasElement ;
  function assertIsHtmlElement (value : any ) : HTMLElement ;
  function assertIsHtmlElementOfType < T = any > (value : any , tagName : ಠ_ಠ.clutz.module$exports$goog$dom$TagName < T > ) : T ;
  function assertIsHtmlEmbedElement (value : any ) : HTMLEmbedElement ;
  function assertIsHtmlFormElement (value : any ) : HTMLFormElement ;
  function assertIsHtmlFrameElement (value : any ) : HTMLFrameElement ;
  function assertIsHtmlIFrameElement (value : any ) : HTMLIFrameElement ;
  function assertIsHtmlImageElement (value : any ) : HTMLImageElement ;
  function assertIsHtmlInputElement (value : any ) : HTMLInputElement ;
  function assertIsHtmlLinkElement (value : any ) : HTMLLinkElement ;
  function assertIsHtmlObjectElement (value : any ) : HTMLObjectElement ;
  function assertIsHtmlScriptElement (value : any ) : HTMLScriptElement ;
  function assertIsHtmlTextAreaElement (value : any ) : HTMLTextAreaElement ;
  function assertIsHtmlVideoElement (value : any ) : HTMLVideoElement ;
}
declare module 'goog:goog.asserts.dom' {
  import dom = ಠ_ಠ.clutz.goog.asserts.dom;
  export = dom;
}
