//!! generated by clutz.
// Generated from crypt/blockcipher.js
declare namespace ಠ_ಠ.clutz.goog.crypt {
  /**
   * Interface definition for a block cipher.
   */
  interface BlockCipher {
    /**
     * Block size, in bytes.
     */
    BLOCK_SIZE : number ;
    /**
     * Decrypt a plaintext block.  The implementation may expect (and assert)
     * a particular block length.
     * @param input Ciphertext. Array of input bytes.
     */
    decrypt (a : number [] | Uint8Array ) : number [] ;
    /**
     * Encrypt a plaintext block.  The implementation may expect (and assert)
     * a particular block length.
     * @param input Plaintext array of input bytes.
     */
    encrypt (a : number [] | Uint8Array ) : number [] ;
  }
}
declare module 'goog:goog.crypt.BlockCipher' {
  import BlockCipher = ಠ_ಠ.clutz.goog.crypt.BlockCipher;
  export default BlockCipher;
}
