//!! generated by clutz.
// Generated from crypt/hashtester.js
declare namespace ಠ_ಠ.clutz.goog.crypt.hashTester {
  /**
   * Runs basic tests.
   * @param hash A hash instance.
   */
  function runBasicTests (hash : ಠ_ಠ.clutz.goog.crypt.Hash ) : void ;
  /**
   * Runs block tests.
   * @param hash A hash instance.
   * @param blockBytes Size of the hash block.
   */
  function runBlockTests (hash : ಠ_ಠ.clutz.goog.crypt.Hash , blockBytes : number ) : void ;
  /**
   * Runs performance tests.
   * @param hashFactory A hash factory.
   * @param hashName Name of the hashing function.
   */
  function runPerfTests (hashFactory : ( ) => ಠ_ಠ.clutz.goog.crypt.Hash , hashName : string ) : void ;
}
declare module 'goog:goog.crypt.hashTester' {
  import hashTester = ಠ_ಠ.clutz.goog.crypt.hashTester;
  export = hashTester;
}
