//!! generated by clutz.
// Generated from crypt/sha224.js
declare namespace ಠ_ಠ.clutz.goog.crypt {
  /**
   * SHA-224 cryptographic hash constructor.
   */
  class Sha224 extends ಠ_ಠ.clutz.goog.crypt.Sha2 {
    private noStructuralTyping_goog_crypt_Sha224 : any;
    /**
     * SHA-224 cryptographic hash constructor.
     */
    constructor ( ) ;
  }
}
declare module 'goog:goog.crypt.Sha224' {
  import Sha224 = ಠ_ಠ.clutz.goog.crypt.Sha224;
  export default Sha224;
}
